services:
  # PostgreSQL database
  postgres:
    image: postgres:latest
    container_name: clinic-postgres
    platform: linux/arm64/v8
    command: [ "--max_connections=1000" ]
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: clinic
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Volumes for data persistence
volumes:
  postgres_data:
